### ISSUE TITLE
Compile issue: matio.h no such file or directionary

### ISSUE THREAD

**Issue by mislulu** [SSAW14/LearnableDilationNetwork#1]
Hello,
I have installed the BVLC version caffe and run correctly.
I came across a bug "hdf5.h : no such file or dictionary" while trying to make all in this dilation caffe folder.I change the INCLUDE_DIR and LIBRARY_DIR( https://github.com/BVLC/caffe/issues/4808). But I came up with a new error "matio.h: no such file or dictionary".  I have also downloaded and installed the matio.  How should I change the Makefile.config? Can anyone give me some tips?

**Comment by SSAW14** [comment]
Hi,

Please check the link (https://bitbucket.org/aquariusjay/deeplab-public-ver2)
for installing matio.
To debug the dilation part, I install matio to use the mat_write_layer.
Hope it helps!

Best,
Yang

**Comment by mislulu** [comment]
Thanks for your help.
I have installed the matio again using sudo and solve the problem
download the matio package and unzip https://sourceforge.net/projects/matio/
install the matio in the terminal:
                                                $cd matio-1.5.11 
                                               $ ./configure  
                                               $make 
                                               $make check  
                                               $sudo make install
